version: '3.3'
services:
  db:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER="YOUR USER"
      - POSTGRES_PASSWORD="YOUR PASSWORD"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "YOUR EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "YOUR PASSWORD"
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin/data

volumes:
  db:
    driver: local
  pgadmin:
    driver: local